### ISSUE TITLE
No Example of using DateTime Column

### ISSUE THREAD

**Issue by CT83** [plumdog/flask_table#100]
Happy to find this great package I have implemented it in production! 🎉 
But even after extensive searching I failed to find an example stating how to use `DateTime`  Column. 
I don't know if this is the correct place to ask this question. 
Any help would be greatly appreciated. 🙇 
<br>
Found this in the docs

> Formats a datetime from the item. Can specify a datetime_format to use, which defaults to 'short', which is passed to babel.dates.format_datetime.

Could someone please post a minimal working example of `DateTime` ? My current Columns show time in the long format including pico seconds (maybe)

**Comment by plumdog** [comment]
I agree a proper example would be well worth adding.

Basic usage would look something like:
```
class MyTable(Table):
    datetime = DatetimeCol(
        'DateTime Heading',
        datetime_format="YYYY-MM-dd hh:mm")

items = [dict(datetime=datetime.datetime.now())]
mytable = MyTable(items)
```

The argument you pass as `datetime_format` is passed on to [Babel's `format_datetime` as the `format` argument](http://babel.pocoo.org/en/latest/api/dates.html#babel.dates.format_datetime), defaulting to `"short"`.

So what it actually displays depends the current locale. If you pass a custom format, Babel uses different [letters to `.strftime` for formatting](http://babel.pocoo.org/en/latest/dates.html#pattern-syntax).

Which is all a touch opaque, really, and worth my documenting properly.

Hopefully that's helpful for the time being. If there's still something not clear or not working for you, let me know and I'll try to help, and get the documentation updated.

**Comment by CT83** [comment]
Oh! Awesome thanks for the quick reply! I will try implementing it and get back to you soon. 
Maybe include it in the docs too if you have the time. Great Docs, easy to use. I am really surprised more people aren't using Flask-Table.

**Comment by CT83** [comment]
I tried the code you suggested, here.
```
class PostTable(Table):
    def sort_url(self, col_id, reverse=False):
        pass

    no = Col('#')
    classes = ['table', 'table-hover', 'table-striped']
    date_posted = DatetimeCol('Date', datetime_format="dd-MM-YYYY hh:mm:ss")
    title = Col('Title')
    content = Col('Content')
    image = Col('Image')
    link = LinkCol('View', 'Posters.view_post', url_kwargs=dict(url='link'))
    social_network = Col('Social Network')


```
But I get an **AttributeError: 'NoneType' object has no attribute 'first_week_day'**. 
Any suggestions?

**Comment by plumdog** [comment]
Sounds like Babel isn't finding a locale to use. It uses some environment variables: `LC_TIME`, `'LANGUAGE`, `LC_ALL`, `LC_CTYPE`, `LANG`. Or you can configure a locale as in https://pythonhosted.org/Flask-Babel/#configuration

You can test this by running `import babel; babel.default_locale('LC_TIME')`. That needs to return a `Locale` object, not None.

**Comment by plumdog** [comment]
Hopefully the combination of those two PRs gives a bit of help. And looking through [the new bit in the README](https://github.com/plumdog/flask_table#babel-configuration) should be helpful too.

**Comment by CT83** [comment]
Yip! This issue can be closed! Thanks for all your help.
