### ISSUE TITLE
passing a csrf_token in the ButtonCol

### ISSUE THREAD

**Issue by bmjjr** [plumdog/flask_table#103]
Having trouble to pass a flask_wtf csrf_token through the form_hidden_fields in your ButtonCol.  

Seems like this should work:
```
ButtonCol(lazy_gettext('Edit'), 'data.list_edit_handler',
                     url_kwargs=dict(get_id='id'),
                     form_hidden_fields=dict(csrf_token="{{ csrf_token() }}"),
                     button_attrs={'class': 'btn btn-primary btn-xs'},
                     allow_sort=False, **kwargs)
```
If it were a regular form then I'd pass the csrf_token like in below html:

```
<form method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
</form>
```

**Comment by plumdog** [comment]
Hi!

The `form_hidden_fields` dict is just turned into some hidden fields in a very straightforward and uninteresting way, (see https://github.com/plumdog/flask_table/blob/v0.5.0/flask_table/columns.py#L342-L349).

So your code above will become
```html
<form method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
</form>
```
in the actual HTML - no templating happens on the values you pass. So what you'll need to do is - in effect, call `csrf_token()` in Python, not in the template.

I suspect if you do
```python
form_hidden_fields=dict(csrf_token=my_get_csrf_token_function())
```
it will work, but you need for `my_get_csrf_token_function()` to do (in Python) the same thing that your `csrf_token()` is doing in your template. I don't think there's a standard in Flask for CSRF stuff, but if you're using `FlaskWTF`, then I think the function you want is actually `flask_wtf.csrf.generate_csrf_token`, so it'd be:
```python
from flask_wtf.csrf import generate_csrf_token
...
form_hidden_fields=dict(csrf_token=generate_csrf_token())
```
You can check if it is doing the right thing by looking at the HTML it generates.

Hope that's useful! Let me know if anything is still not working for you.

**Comment by john-drews** [comment]
has this been figured out? i am running into the same issue. i am adding a view to an existing airflow plugin so i don't have direct app access.

my form works when using the template but i cannot use the function you provided 

any help would be appreciated.

**Comment by plumdog** [comment]
Hi @john-drews I've created a PR (see link above) with an example to show this in action.

Hopefully it show the rough idea of how to get a CSRF token into the forms in the table.
