### ISSUE TITLE
ButtonCol or Link col dynamic routes?

### ISSUE THREAD

**Issue by guzzijones** [plumdog/flask_table#104]
Is it possible to set dynamic routes for a Button or LinkCol.

Current:
```
lass SupTable(Table):
    master_sup_id= Col('ID')
    supplier_name=Col('Supplier Name')
    supplier_state=Col('State')
    supplier_zip=Col('Zip')
    edit = ButtonCol('Edit','administrator.sup_master',url_kwargs=dict(master_sup_id='master_sup_id'))
```
lets say sup master is defined
```
@administrator.route('/supplier/<obj_id:int>')
def sup_master(obj_id):
....
```
except button col would be able to add the obj_id instead of passing an arg.

**Comment by plumdog** [comment]
Hi!

It looks to me that if you pass `url_kwargs=dict(obj_id='master_sup_id')`, you might get what you want. The key of the dict should match the variable names in the route.

I think what you're describing is similar to this example (which uses `LinkCol`, but the idea is the same): https://github.com/plumdog/flask_table/blob/master/examples/simple_app.py There are some [docs too](https://github.com/plumdog/flask_table#more-about-linkcol).

You should be able to run that example and see if it doing the thing you want.

If not, let me know and I'll see if I can help.

**Comment by guzzijones** [comment]
url_kwargs adds to the url as an arg.  It is not extending the url itself.

``` http://127.0.0.1:8080/administrator/suppliers/?master_sup_id=a2z ```

**Comment by guzzijones** [comment]
It works.  I had to do this of course:
```
class SupTable(Table):
    master_sup_id= Col('ID')
    supplier_name=Col('Supplier Name')
    supplier_state=Col('State')
    supplier_zip=Col('Zip')
    edit = ButtonCol('Edit','administrator.sup_master',url_kwargs=dict(obj_id='master_sup_Id'))
...
administrator.route('/supplier/<obj_id:int>')
def sup_master(obj_id):
...
```

If the url_kwargs dict key is the same as the route parameter it works as it should.

**Comment by guzzijones** [comment]
Oh I see you are using url_for.  good work on this btw.

```
   def url(self, item):
        return url_for(self.endpoint, **self.url_kwargs(item))
```

**Comment by lormayna** [comment]
I have the same problem with a post:
This is my table:
`
class UserTable(Table):
        user_id = Col('user_id', show=False)
        name = Col('Name')
        surname = Col('Surname')
        detokenize_button = ButtonCol("Detokenize", "detokenize", form_hidden_fields=dict(id=user_id), button_attrs={"class" : "btn btn-warning"} )
`

and this is the route:
`
@app.route("/detokenize", methods=['POST'])
def detokenize():
`

Therefore, when I click the button I got this:
`
(Pdb) p request.form
ImmutableMultiDict([('id', '<flask_table.columns.Col object at 0x7f55c5a88358>')])
(Pdb) p request.form['id']
'<flask_table.columns.Col object at 0x7f55c5a88358>'
(Pdb) 
'<flask_table.columns.Col object at 0x7f55c5a88358>'
`

**Comment by plumdog** [comment]
I think what you're trying to do is take values from the row and include them in the post data, which isn't currently possible, but could be added.

(FWIW: The reason the string repr of a column is arriving in the `detokenize` method is because `form_hidden_fields` just adds static values as hidden fields (have a look at the HTML it generates) and you're passing `user_id` which is a column.)

The best way to achieve what I think you're aiming for would be something like:
```python
from flask_table import Table, Col, ButtonCol
from flask import Flask, request, escape

app = Flask(__name__)

class UserTable(Table):
    name = Col('Name')
    detokenize_button = ButtonCol('Detokenize', 'detokenize', url_kwargs=dict(id='user_id'))

@app.route('/')
def index():
    items = [
        dict(user_id=1, name='User1'),
        dict(user_id=2, name='User2'),
    ]
    table = UserTable(items)
    return table.__html__()

@app.route('/detokenize/<int:id>', methods=['POST'])
def detokenize(id):
    return str(id)

if __name__ == '__main__':
    app.run(debug=True)
```
By setting `url_kwargs=dict(id='user_id')`, this tells the button to take the value of the `user_id` attr from the item, and pass it to the URL as `id`, and use this as the action for the form. So it posts to `detokenize` and you can get the id from the URL.

Hope that helps.

**Comment by guzzijones** [comment]
Yes what plumdog posted is exactly how I did it @lormayna.  Your route will grab the 'id' column value.  This way you can pass parameters to a post from the row of data easily without having to do dancing in your form.  It is handy if you want to then query that table for the row again and create a sqlalchemy object.

**Comment by guzzijones** [comment]
It may be worth posting up in the examples a SSE of this and some CRUD MethodView child classes working together as a pull request.  It seems I am writing a crud api and any help would be appreciated.
