### ISSUE TITLE
Adding classes to table

### ISSUE THREAD

**Issue by gilinson** [plumdog/flask_table#11]
In table.py the current code inserts a space to the class argument. I'm not sure if this is on purpose (I have no familiarity with this package). From what I can tell this prevents the class being set correctly when html is generated.

This could be fixed by removing space from line 53.
`return ' class="{}"'.format(' '.join(self.classes))`

to

`return ' class="{}"'.format(''.join(self.classes))`

**Comment by plumdog** [comment]
Hi, and I'm glad you're using the package!

The space means that if `self.classes` has multiple elements, they will be separated with a space.

Eg, if `classes = ['class1', 'class2']` we will get a table that looks like
```html
<table class="class1 class2">
...
</table>
```

Or if there is only one class, it will just give `class="class1"`.

I've also added `examples/classes.py` to show setting of this attribute.

Let me know if anything is unclear. If you want to post your code that is not setting a class correctly, I'd be happy to look at it.

**Comment by gilinson** [comment]
Its not working like that from my end.

here is a snippet of the python code I have where I set the classes attribute.
`table = ItemTable(items)
table.classes = "table table-bordered table-hover"`

This produces -
`<table class="t a b l e   t a b l e - b o r d e r e d   t a b l e - h o v e r">`

I see that you are supposed to do this:

    table.classes.append("table")
    table.classes.append("table-bordered")
    table.classes.append("table-hover")

That produces the correct result.

**Comment by plumdog** [comment]
You could also do:
```python
table.classes = ['table', 'table-bordered', 'table-hover']
```
or
```python
class MyTable(Table):
    classes = ['table', 'table-bordered', 'table-hover']
    ...
```

I've also added some information to the README [here](https://github.com/plumdog/flask_table/blob/master/README.md#setting-a-class-on-the-table-element).
