### ISSUE TITLE
can't display table data when use Flask-SQLAlchelmy return full column name

### ISSUE THREAD

**Issue by ustandz** [plumdog/flask_table#115]
I have try to use  Flask-SQLAlchelmy with joinload.

result = idb.tbStationType.query.options(joinedload('station'))

and result before in to flask table something like:

    for row in result:
        print(row.tbStation.stationID)

and then pass it to table:
table = tb.tbStation(result)

after pass to flask-table will error:
AttributeError: 'result' object has no attribute 'stationID'

sql statement something like:

SELECT "tbStation"."stationID", "tbStation"."stationName", "tbStation"."stationDesc", "tbStation"."LanIDName", "tbStation"."productID", "tbStation"."factoryID", "tbStation"."stationEquipID", "tbStation"."stationType", "tbStationType"."StationTypeID", "tbStationType"."StationTypeName", "tbStationType"."StationTypeDesc"
FROM "tbStation", "tbStationType"
WHERE "tbStationType"."StationTypeID" = "tbStation"."stationType"

how can i pass join column name in to flask-table

**Comment by ustandz** [comment]
Thank you very much,
Now i can pass value to table.

**Comment by plumdog** [comment]
Great stuff!
