### ISSUE TITLE
functions as url_kwargs

### ISSUE THREAD

**Issue by CheapB** [plumdog/flask_table#117]
Functions are working well with Col using attr or attr_list but I have a hard time figuring out how to use this with LinkUrl

`   prefstorestockprice = Col('Pref.stores in stock', attr_list=['prefstockproductstore','price'])

` where prefstockproductstore is a function returning an object is working fine but I am struggling with  building the url_kwargs from a function. This is what I have tried: 
`prefstorestockprice = LinkCol('Pref.stores in stock','productstoreupsert', url_kwargs=dict(productid='prefstockproductstore.productid',storeid='prefstockproductstore.storeid'),attr='prefstockproductstore.price' )
`
but I am getting werkzeug.routing.BuildError: Could not build url for endpoint 'productstoreupsert'. Did you forget to specify values ['productid', 'storeid']?

**Comment by CheapB** [comment]
I have a hard time reproducing this is a simple example w/o a database etc. however it seems like it is ignoring the 2nd element of the dict. The error message changes dependent on the sequence of the url_kwargs 

`prefstorestockprice2 = LinkCol('Pref.stores in stock', 'productstoreupsert', url_kwargs=dict(storeid='prefstockproductstore.storeid',productid='productid'), attr='prefstockproductstore.price')

werkzeug.routing.BuildError
werkzeug.routing.BuildError: Could not build url for endpoint 'productstoreupsert' with values ['productid']. Did you forget to specify values ['storeid']?	

prefstorestockprice2 = LinkCol('Pref.stores in stock', 'productstore', url_kwargs=dict(productid='productid',storeid='prefstockproductstore.storeid'), attr='prefstockproductstore.price')

werkzeug.routing.BuildError
werkzeug.routing.BuildError: Could not build url for endpoint 'productstoreupsert' with values ['productid']. Did you forget to specify values ['storeid']?	`

the below examples works well: 
`    storeid              = Col('storeid', attr='prefstockproductstore.storeid')
    prefstorestockprice  = Col('Pref.stores in stock', attr='prefstockproductstore.price')
`

**Comment by CheapB** [comment]
I have a hard time reproducing with a smaller example, however this works: 
`storeid              = Col('storeid', attr='prefstockproductstore.storeid')`

but if I am using the same value in url_kwarg is 
`prefstorestockprice2 = LinkCol('Pref.stores in stock', 'productstoreupsert', url_kwargs=dict(storeid='prefstockproductstore.storeid',productid='productid'), attr='prefstockproductstore.price')
`
werkzeug.routing.BuildError: Could not build url for endpoint 'productstoreupsert' with values ['productid']. Did you forget to specify values ['storeid']

**Comment by plumdog** [comment]
Hi @CheapB 

I think what you're seeing is not a flask-table thing as such, but rather a general flask error if you pass `None` to a url. Under the hood:
```python
LinkCol('MyLink', 'myendpoint', url_kwargs=dict(foo='bar'))
```
will get a url by doing `url_for('myendpoint', foo=item.bar)` (or `item['bar']` or `item.bar()` or whatever using the lookup logic). If one of the kwargs passed to `url_for` is `None`, then you'll get that error, eg:
```python
from flask import Flask, url_for

app = Flask(__name__)

@app.route('/foo/<int:id>')
def foo(id):
    return str(id)

app.config.update({'SERVER_NAME': 'localhost'})

with app.app_context():
    print(url_for('foo', id=99))
    print(url_for('foo', id=None))
```
outputs:
```
http://localhost/foo/99
Traceback (most recent call last):
  File "functions_as_url_kwargs.py", line 13, in <module>
    print(url_for('foo', id=None))
  File "/home/andrew/flask_table/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/andrew/flask_table/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/andrew/flask_table/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/andrew/flask_table/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/andrew/flask_table/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'foo'. Did you forget to specify values ['id']?
```

So I think what the exception you're getting is trying to say is: "when I call/lookup `prefstockproductstore.storeid` on the item, I get `None` which errors when then calling `url_for`". Check that attribute/method is getting what you expect for every item you're passing to the table.

Hope that helps!
