### ISSUE TITLE
Give the possibility to add a specific class to thead

### ISSUE THREAD

**Issue by pdonorio** [plumdog/flask_table#12]
Hello,
if you see how css frameworks work 
(e.g. bootstrap http://v4-alpha.getbootstrap.com/content/tables/#table-head-options) 
it would be conveniente to have a way to add a thead class like the table class option.

For now i patched with:
```
class ItemTable(Table):
    def thead(self):
        return '<thead class="thead-default"><tr>{}</tr></thead>'\
            .format(''.join( (self.th(col_key, col) \
            for col_key, col in self._cols.items() if col.show)))
```

Thanks for this great plugin,
Paolo

**Comment by pdonorio** [comment]
As a comment, i also had to implement a new `create_table` to use dynamically the previous declared `ItemTable`:

```
def create_table(name, tableclass):
    return type(name, (tableclass,), {})
```

Could this method updated too?
Should i open a separate issue for this?

Thanks again!

**Comment by plumdog** [comment]
Hi, I've opened a PR with my changes for the thead class. Sounds like a excellent idea!

As for the `create_table` changes, I've [made a start](https://github.com/plumdog/flask_table/compare/inherit_when_creating_table) but it's currently failing my tests. I'll have a bit more of a look later.
Could I ask you to create a new issue for the `create_table` changes?

**Comment by pdonorio** [comment]
It works... almost!

I start from here:
```python
""" A table test """

from flask_table import Col, create_table

table_name = 'test'
colname = 'coltest'
classes = ['test_one', 'test-hover']
head_classes = ['test_one', 'test-hover']
data = [
    {'coltest': 'one'},
    {'coltest': 'three'},
    {'coltest': 'two'},
]
```

With this syntax it works:
```
TableCls = create_table(table_name)
TableCls.add_column(colname, Col(colname))
TableCls.classes = classes

tmp = TableCls(items=data, thead_classes=head_classes)
print(tmp.__html__())

# <table class="test_one test-hover">
# <thead class="test_one test-hover"><tr><th>coltest</th></tr></thead>
# <tbody>
# <tr><td>one</td></tr>
# <tr><td>three</td></tr>
# <tr><td>two</td></tr>
# </tbody>
# </table>
```

While in this way, which is the way i am using it, it doesn't:
```
TableCls = create_table(table_name)
TableCls.add_column(colname, Col(colname))
TableCls.classes = classes
TableCls.head_classes = head_classes
tmp = TableCls(items=data)
print(tmp.__html__())

# <table class="test_one test-hover">
# <thead><tr><th>coltest</th></tr></thead>
# <tbody>
# <tr><td>one</td></tr>
# <tr><td>three</td></tr>
# <tr><td>two</td></tr>
# </tbody>
# </table>
```

If you could fix the second example, it would make a lot of difference in my automatic tables from sqlalchemy models.

Thanks so much,
Paolo

**Comment by plumdog** [comment]
Oops, got a bit carried away with merging things!
Might just be a typo in your example code, but `TableCls.head_classes` should be `TableCls.thead_classes`. Does that fix it?

**Comment by pdonorio** [comment]
Ooops shame on me.
The problem was on that typo!!

You can close here, it works fantastic ;)

**Comment by plumdog** [comment]
\o/
