### ISSUE TITLE
key error with babel

### ISSUE THREAD

**Issue by lisjump** [plumdog/flask_table#120]
My error appears to be fairly identical to this unsolved issue and I see reference to it in other places as well.  Do you have an idea as to what triggers it?  I've played around a bit with ordering and such and have had no luck.

https://stackoverflow.com/questions/50768936/keyerror-babel-related-to-init-py-not-using-babel-explicitly

**Comment by plumdog** [comment]
Hi @lisjump,

Do you have a minimal example flask app that reproduces this error? That stackoverflow question indicates that the error only occurs when posting to a particular endpoint.

I suppose it has to be that somewhere Babel is not initialising properly on some endpoints, but I'm guessing, really.

If you can post a minimal app (something that looks a bit like https://github.com/plumdog/flask_table/blob/master/examples/simple_app.py) that demonstrates this error, I'll be able to investigate.

**Comment by lisjump** [comment]
Sorry for the lack of debugging on my part (although I thought I had debugged it thoroughly).  The error was actually happening upon trying to run my main.py, but I was calling including flask-tables in my routes.py.

I went to add it to main.py to show that it was throwing the error immediately and that seems to have fixed it.  I'm not sure why, but I'll take it.

**Comment by jbhanks** [comment]
> Sorry for the lack of debugging on my part (although I thought I had debugged it thoroughly). The error was actually happening upon trying to run my main.py, but I was calling including flask-tables in my routes.py.
> 
> I went to add it to main.py to show that it was throwing the error immediately and that seems to have fixed it. I'm not sure why, but I'll take it.

I just had a similar issue. In my case, I had to import flask_tables in my main __init__.py and then again in the actual blueprint using it.   Just importing it within the route gave me the `babel` key error. I'm curious as to why.
