### ISSUE TITLE
cannot set attributes on table

### ISSUE THREAD

**Issue by ulkeizsofi** [plumdog/flask_table#122]
__init__() got an unexpected keyword argument 'html_attrs'

If I put it in the table as a field, it does not give an error, but the result is not changed.

**Comment by plumdog** [comment]
Hi @ulkeizsofi, can you post your code that reproduces this issue? If you can reduce it to the smallest example that errors in this way, that would be useful.

**Comment by ulkeizsofi** [comment]
Hi, i have found the problem. My flask_python was not the latest release. Sorry for bothering you.

**Comment by plumdog** [comment]
No probs!
