### ISSUE TITLE
How to manipulate th tag

### ISSUE THREAD

**Issue by LuckyPigeon** [plumdog/flask_table#131]
I want to use bootstrap attribute `<th scope="row"></th>` in my code, my I can't find the way in docs, how can I achieve this?

**Comment by painor** [comment]
have you found a way? I want to do something similar but I couldn't find a way without editing most of the code

**Comment by plumdog** [comment]
I think that https://github.com/plumdog/flask_table/blob/master/examples/column_html_attrs.py#L37 is an example of what you're after.

This is covered (a bit, at least) in one of the bullet points here https://github.com/plumdog/flask_table#extra-things
