### ISSUE TITLE
Enable documentation generation inside the repo

### ISSUE THREAD

**Issue by pdonorio** [plumdog/flask_table#16]
Have you consider using [Sphinx](http://sphinx-doc.org/) or similar?
It may allow other people may help you write documentation, for examples with PR.

In case you don't have time or will, 
i may prepare a PR to include documentation generated in markdown with [mkdocs](http://www.mkdocs.org/). I may simply convert your readme in mkdocs template so that you can enable autogeneration on websites like [readthedocs](http://readthedocs.org/).

Paolo

**Comment by plumdog** [comment]
That would be ace! I'd love to get a readthedocs site setup. There are already things that are missing from the README that I should add.
I'd like to start with whatever the simplest readthedocs configuration is, which would probably be Sphinx.
Things that are currently lacking from the README (an incomplete list!):
- Dynamic table inheritance, and how columns are inherited.
- Failure modes and common gotchas
- How to run the tests/examples

**Comment by pdonorio** [comment]
Hey, 
i just [forked your repo](https://github.com/pdonorio/flask_table) to give you an example with mkdocs, 
see [this commit](https://github.com/pdonorio/flask_table/commit/edad84929fc6cfba2545a2dfeeb453b1ff02783b), it was very quick.

Here is the example automatically hooked to readthedocs:
http://example-for-flask-table.readthedocs.org/en/latest/

Paolo

**Comment by plumdog** [comment]
Using your commit as a template, I have added read the docs support (finally!).
See #18 and http://flask-table.readthedocs.org/en/latest/
For reasons of laziness and simplicity, I have just used the README as it stands. This means that we don't have to replicate the text between the README and the documentation.

**Comment by plumdog** [comment]
@pdonorio Just noticed that https://example-for-flask-table.readthedocs.io/en/latest/ is still up and is - unsurprisingly - out of date. If possible, could you deactivate or delete it?

**Comment by pdonorio** [comment]
Oops sorry.
Now it's gone.

**Comment by plumdog** [comment]
No worries! Thanks for that. :+1:
