### ISSUE TITLE
Support for nesting tables

### ISSUE THREAD

**Issue by jonathanunderwood** [plumdog/flask_table#27]
I have a use case where I want to nest a table inside the main table in one of the columns. I've managed to get something working by subclassing Col for that column, and hand producing the nested table html inside the td_format method for that Col subclass.

But it would be nice if there was a more elegant way of allowing nesting. I'm playing around with various ideas currently, but haven't come up with a decent deign, so I thought I'd open an issue to see if you could see an easy way to achieve this :).

**Comment by plumdog** [comment]
Interesting! I feel like subclassing Col to take a table class is the right way to go, but I'll have a look and see what seems nice.

**Comment by jonathanunderwood** [comment]
The pattern I have so far is something like this (sketch, the actual code is different):

````python
class SubTable(Table):
    id = LinkCol('id', 'single_item',
                         url_kwargs=dict(id='id'), attr='id')

class SubCol(Col):
    def td_format(self, ids):
        t = SubTable(ids)
        return t.__html__()
````

**Comment by jonathanunderwood** [comment]
Aside: I wish it was posible to suppress column headings, as in the nested table, the headings are repeated for every row. I can see why that would be useful, but in my case it isn't :)

**Comment by jonathanunderwood** [comment]
Actually, the most general thing I could come up with is this:

````python
class NestedTableCol(Col):
    def __init__(self, name, table_class, **kwargs):
        super(NestedTableCol, self).__init__(name, **kwargs)
        self.table_class = table_class

    def td_format(self, content):
        t = self.table_class(content).__html__()
        return t
````

where the table_class argument is a previously defined subclass of Table defining the structure of the nested table. Seems to work quite well - let me know what you think, might be nice to include it :)

**Comment by jonathanunderwood** [comment]
#28 is a PR implementing this, along with documentation, a test, and a simple example - let's continue discussion there.
