### ISSUE TITLE
Table attributes

### ISSUE THREAD

**Issue by carolinux** [plumdog/flask_table#33]
What if I want to add something like `<table border=1>`. I think right now it's not possible (and I know I could do it with CSS classes) - but would you be OK if I do a pull request implementing this?

**Comment by plumdog** [comment]
Of course! That sounds like a good idea. You might want to make it fairly general, so that things like https://github.com/plumdog/flask_table/issues/31 can also be catered for.

**Comment by carolinux** [comment]
@plumdog Ok - I will try to do it soon! Thanks

**Comment by carolinux** [comment]
I wonder, should I keep table_id as a special case for backwards compatibility?

**Comment by carolinux** [comment]
The code  would be much simpler with a general attribute kwarg though that expects a dict.

**Comment by plumdog** [comment]
Could it be an attributes dict, but then update that dict with values passed as `table_id` or `classes`? That way it keeps backwards-compatibility, and the attributes dict stores everything.

**Comment by plumdog** [comment]
This should be catered for by #44 as you can now set `html_attrs = {'table_id': 'mytable', 'border': '1', 'my-data-attr': 'my-data-value'}` on your table class.
