### ISSUE TITLE
sortable.py question

### ISSUE THREAD

**Issue by cdamundsen** [plumdog/flask_table#36]
I'm trying to use flask-table to create sortable tables in a Flask app I've created. I've been playing around with the sortable.py example and have hit a problem.

The issue I'm having is that I don't know what the columns are going to be until runtime. Is there a way to initialize the SortableTable class with Col instances at runtime?

I tried this
~~~~
class SortableTable(Table):
    def __init__(self, *args, **kwargs):
        super(SortableTable, self).__init__(*args, **kwargs)
        SortableTable.__dict__['id'] = Col("ID")
        SortableTable.__dict__['name'] = Col("Name")
        SortableTable.__dict__['Description'] = Col("Description")
        SortableTable.__dict['link'] = LinkCol('Link', 'flask_link', url_kwargs=dict(id='id'), allow_sort=False)

    etc
~~~~
With hopes that I could later instantiate table by including a list of (attrName, colTitle) tuples to loop through.

But when I call `table = SortableTable(Item.get_sorted_by(sort, reverse), sort_by=sort, sort_reverse=reverse)`

I get an exception saying the dict_proxy does not support item assignment. I thought that perhaps I needed to set up the columns before calling the superclass' __init__ method, so I put the super call after __dict__ assignment lines and got the same error.

Is there a way to define columns at runtime?

Thanks,
Craig

**Comment by cdamundsen** [comment]
Wait! I just read some more of the docs and saw something about dynamic tables. I'm going to try combining them

**Comment by cdamundsen** [comment]
Using create_table worked great.

**Comment by plumdog** [comment]
Yup, you can either use `create_table` or

```python
class MyTable(Table):
    # ... some standard columns here

for col_name in extra_cols:
    MyTable.add_column(col_name)
```
If you reckon the docs could do with some fleshing out on this topic, let me know.
