### ISSUE TITLE
Rendering a Flask-table for a wtforms FieldList(FormField(SomeForm)

### ISSUE THREAD

**Issue by smewp** [plumdog/flask_table#38]
Hi, I've been trying to modify this library to be able to generate a dynamic table with input fields that can work with a FieldList(FormField(SomeForm) structure.   I have a form like below:

    class InputGridRecordForm(NavForm):
        """A form for entering inputgrid record row data"""
        id = IntegerField('Continent Record ID')
        select = BooleanField('Select')
        stringcol1 = StringField('String Col #1')
        intcol1 = IntegerField('Int Col #1')

    class InputGridTableForm(NavForm):
        """A form for one or more InputGridRecords"""
        gridtblrecords = FieldList(FormField(InputGridRecordForm), min_entries=1)

If I render the body of this form **without Flask-Table** then the `<tbody>` basically looks like below:

    <tbody>
        {{ form.csrf_token }}
        {% for grid_record in form.gridtblrecords %}
        <tr>
            {% for field in grid_record %}
            <td>{{ field() }}</td>
                {% endfor %}
         </tr>
        {% endfor %}
    </tbody>

It would be nice if this worked with flask-table but I need to find a way to get the jinja for-loops working right and it's been a no-go so far. Here is (some) of what I've tried.  

Override tbody for the outer loop:

        def tbody(self):
            out = [self.tr(item) for item in self.items]
            if out:
                return Template('<tbody>{% for form in form.gridtblrecords %}'
                                '\n{0}\n{% endfor %}'
                                '</tbody>').render(form=self.form).format('\n'.join(out))
           else:
               return '' 

Override tr_format for the inner loop:

        def tr_format(self, item):
        """Returns the string that is formatted with the contents of the
        tr. Override this if you want to alter the attributes of the
        tr.
        """
        return Template(
                        '<tr>'
                        '{% for field in grid_record %}'
                        '{}'
                        '{% endfor %}'
                        '</tr>'
                        ).render(form=self.form)

I've done a few different things for the column classes but it seems I should just be able to return a string of the different fields in a jinja template braces and it should render in the tr_format.

    class InputStringCol1(Col):
         """Make a column that can accept inputs"""
             def td_format(self, content):
             """formats the <td> to accept an input"""
             safe_content = super(InputStringCol1, self).td_format(content)
             return ='{{ field.stringcol1 }}'

Anyway, want to check to see if you've already tackled this or have any feedback - which is much appreciated!

**Comment by plumdog** [comment]
I hacked together something that I hope illustrates the approach I would take - assuming I've understood correctly:

```python
from wtforms.form import Form
from wtforms.fields import FieldList, FormField, IntegerField, BooleanField, StringField
from jinja2 import Template

from flask_table import Table, Col

from bs4 import BeautifulSoup


def pretty_html(html):
    return BeautifulSoup(html, 'html.parser').prettify()


class InputGridRecordForm(Form):
    """A form for entering inputgrid record row data"""
    id = IntegerField('Continent Record ID')
    select = BooleanField('Select')
    stringcol1 = StringField('String Col #1')
    intcol1 = IntegerField('Int Col #1')

class InputGridTableForm(Form):
    """A form for one or more InputGridRecords"""
    gridtblrecords = FieldList(FormField(InputGridRecordForm), min_entries=1)


def from_template(form):
    template = '''
    <table>
        <tbody>
            {{ form.csrf_token }}
            {% for grid_record in form.gridtblrecords %}
                <tr>
                    {% for field in grid_record %}
                        <td>{{ field() }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>'''
    return pretty_html(Template(template, autoescape=True).render(form=form))


def from_flask_table(form):
    class MyTable(Table):
        id = Col('ID')
        select = Col('Select')
        stringcol1 = Col('Stringcol1')
        intcol1 = Col('Intcol1')

        def thead(self):
            # No thead because there was none in the example
            return ''

    return pretty_html(
        Template(r'{{ table }}', autoescape=True).render(table=MyTable(form.gridtblrecords))
    )

form = InputGridTableForm()
html_from_template = from_template(form)
html_from_flask_table = from_flask_table(form)

print 'From template:'
print '=============='
print html_from_template

print 'From flask_table:'
print '================='
print html_from_flask_table

print '================='

if html_from_template == html_from_flask_table:
    print 'All matches'
else:
    print 'Not the same'
```

The gist of which is: you should just be able to use the contents of the `from_flask_table` function to do what you need to do. If you give a table an iterable of things with attributes, and those attributes match the columns of the table, then they will be displayed (hence why the naming of the columns matches that of the form).

I've also overridden the `thead()` of the table. That's really just so it matches the example template that you posted, you may or may not want to restore this.

Hopefully some of that is useful.

**Comment by smewp** [comment]
@plumdog This is great - the from_flask_table(form) method should work in this case - thanks so much for the feedback. I'm still hitting a snag in the view around the required query and finickiness of this wtforms FieldList(FormField) structure, for example I think I may need to use the populate_obj() or process() method in some way that I'm just not getting yet. But, when I finally get it worked out, I'll follow up, maybe it can be useful to update examples/docs.

**Comment by smewp** [comment]
Following up, the `from_flask_table(form)` method works for my use case with the FieldList(FormField(SomeForm) structure, which I'm loading existing data from a database into the form on the GET request and then also updating the database on the POST request for any changes or new records (not shown in below view).  

For me, the secret sauce to get it working was figuring out to include the `data=MultiDict(data))` part in the form declaration, and then this `form` is  passed into the `from_flask_table(form)` method that you describe above. This relevant part of the view is below.  
   
    `<the basic imports go here>`
    from werkzeug.datastructures import MultiDict
    
    @blueprint.route('/list/inputgrid', methods=['GET', 'POST'])
    def list_inputgrid():
        """workout the basic input grid."""
        records = InputGrid1.query.order_by('id').all()
        data = {'gridtblrecords': records}
        form = InputGridTableForm(request.form, data=MultiDict(data))

        return render_template('inputgrid.html', form=form)

**Comment by plumdog** [comment]
:+1: Sounds good to me. I'm not super familiar with the workings of WTForms, but glad you've got it sorted.

**Comment by premkarat** [comment]
> Following up, the `from_flask_table(form)` method works for my use case with the FieldList(FormField(SomeForm) structure, which I'm loading existing data from a database into the form on the GET request and then also updating the database on the POST request for any changes or new records (not shown in below view).
> 
> For me, the secret sauce to get it working was figuring out to include the `data=MultiDict(data))` part in the form declaration, and then this `form` is passed into the `from_flask_table(form)` method that you describe above. This relevant part of the view is below.
> 
> ```
> `<the basic imports go here>`
> from werkzeug.datastructures import MultiDict
> 
> @blueprint.route('/list/inputgrid', methods=['GET', 'POST'])
> def list_inputgrid():
>     """workout the basic input grid."""
>     records = InputGrid1.query.order_by('id').all()
>     data = {'gridtblrecords': records}
>     form = InputGridTableForm(request.form, data=MultiDict(data))
> 
>     return render_template('inputgrid.html', form=form)
> ```

@bmjjr can  you please paste your post call magic for reference.
