### ISSUE TITLE
Add option to specify attrs on LinkCol anchor and ButtonCol button

### ISSUE THREAD

**Issue by plumdog** [plumdog/flask_table#55]

**Comment by PnPie** [comment]
Can you give an example like what kind of attrs to add ?

**Comment by plumdog** [comment]
Any HTML attrs. Eg, being able to pass more things [here](https://github.com/plumdog/flask_table/blob/master/flask_table/columns.py#L278). (It seems I already did this for the `<button>` in `ButtonCol` in https://github.com/plumdog/flask_table/commit/ab3837eee6a7b8f039f27f98172a28685bc059f8).
