### ISSUE TITLE
setting id on table tag

### ISSUE THREAD

**Issue by ksk438** [plumdog/flask_table#78]
How can i set the table tag id to 'table' so the HTML output looks like this: '`<table `id='table'>`'`
Is there a way to pass any tags i want?

**Comment by plumdog** [comment]
Hi!

You can set `html_attrs` in your class, so `html_attrs = {'id': 'table'}` should do it for your example.

---------------

More generally though, this is a think that is probably a bit lacking in the docs, and could do with some standardisation. (I had to poke through the code to remember how to set these html attributes.)

I'll open a more general ticket for looking at that.
