### ISSUE TITLE
creting a table

### ISSUE THREAD

**Issue by pelos** [plumdog/flask_table#87]
I am trying to make a dynamic table.
created the table,  added the columns, but now how to I pass my list of dictionaries?

    TableCls = flask_table.create_table('TableCls')
    for i in range(0, 20):
        TableCls.add_column(str(i), flask_table.Col(str(i)))

    TableCls.items = items_list  # not sure how to inject my itemlist into the flask_table class so it render properly with flask.

    return render_template(table=TableCls)

thanks =)

**Comment by plumdog** [comment]
Hi,

So `TableCls` really is a class, and so you can use it just like a class defined with `class TableCls: ...`

Therefore, in your example above you would do something like:
```python
TableCls = flask_table.create_table('TableCls')
for i in range(0, 20):
    TableCls.add_column(str(i), flask_table.Col(str(i)))

table = TableCls(items)
return render_template(table=table)
```

There's also an example here that might be helpful: https://github.com/plumdog/flask_table/blob/master/examples/dynamic.py

Hope that's useful, and thanks for using flask-table!

**Comment by pelos** [comment]
Thanks for making it :) I will give it a try :)

Sent from Yahoo Mail on Android 
 
  On Thu, Dec 21, 2017 at 3:56 PM, Andrew Plummer<notifications@github.com> wrote:   
Hi,

So TableCls really is a class, and so you can use it just like a class defined with class TableCls: ...

Therefore, in your example above you would do something like:
TableCls = flask_table.create_table('TableCls')
for i in range(0, 20):
    TableCls.add_column(str(i), flask_table.Col(str(i)))

table = TableCls(items)
return render_template(table=table)
There's also an example here that might be helpful: https://github.com/plumdog/flask_table/blob/master/examples/dynamic.py

Hope that's useful, and thanks for using flask-table!

**Comment by plumdog** [comment]
Closing, hopefully the above was useful. Please reopen and let me know if you have other questions about this.
