### ISSUE TITLE
Pandas

### ISSUE THREAD

**Issue by jemshit** [plumdog/flask_table#93]
Any direct integration available to pandas DataFrame object to create tables?

**Comment by plumdog** [comment]
Hi! So there's nothing currently that does anything special for `DataFrame`. I haven't used pandas, but from the docs for DataFrame, I think you could do something a bit like:

```python
from flask_table import Col, create_table
import pandas as pd

data = dict(
    a=[1, 2, 3],
    b=['row1', 'row2', 'row3'])
dataframe = pd.DataFrame(data=data)

def as_table(df):
    MyTable = create_table()
    for col in df.columns:
        MyTable.add_column(col, Col(col))
    return MyTable(row for _, row in df.iterrows())

table = as_table(dataframe)
print table.__html__()
```

Something like that might be helpful, but if you need something that does better conversion of types to `Col` classes, you might need to write something a bit more custom.

Like I said, I have essentially no experience with pandas, so if you have any thoughts or examples of how `flask_table` could better accommodate a `DataFrame`, I'd be very interested. (Though any changes to `flask_table` should probably stay as general as possible, and certainly it shouldn't gain a dependency on `pandas`). I wonder if some way of registering a conversion of types to Col classes would be workable.

Thanks for this idea!
