### ISSUE TITLE
freezing table headers

### ISSUE THREAD

**Issue by elgaucho79** [plumdog/flask_table#94]
Hi Andrew,

I was wondering if there is a way to freeze the header to support users with long lists.  Once you start to scroll, the header disappears. 
I look for something like in Excel, Freeze header.
Was already looking into bootstrap, but could not find anything usefull, except responsive table definition which was not doing anything different then before:

![image](https://user-images.githubusercontent.com/32534197/34439793-cb163d82-ecb0-11e7-913d-0bba97ae768f.png)

regards
Michael

**Comment by plumdog** [comment]
Hi,

Freezing the headers is something you'd need to tackle with CSS, and I don't think Bootstrap supports it by itself.

There's some stuff here that might help: https://stackoverflow.com/questions/21168521/scrollable-table-with-fixed-header-in-bootstrap

Hopefully that helps.
