### ISSUE TITLE
RawCol using Jinja2 statements

### ISSUE THREAD

**Issue by elgaucho79** [plumdog/flask_table#95]
Hi Andrew,

I am trying to implement a select2 box for each row into my table. The select2 box is using Jinja2 statements with values provided by the python app itself:

![image](https://user-images.githubusercontent.com/32534197/34527919-78cdb60e-f0a7-11e7-8c3a-26ab78563eda.png)

so, in my table definition I copied the select box coding into a RawCol for this purpose and it seems the table is not able to render this in the right order or he tries to instantiate the select box already by the time of table creation and not at runtime.

![image](https://user-images.githubusercontent.com/32534197/34528510-708b7f4c-f0a9-11e7-9df5-c743b8773410.png)
![image](https://user-images.githubusercontent.com/32534197/34528386-1d8982bc-f0a9-11e7-8dd0-d01aa3de9aef.png)

result:
![image](https://user-images.githubusercontent.com/32534197/34528549-866d737e-f0a9-11e7-8f92-e5e8d8ec976a.png)

The same seems to be using wtforms:
![image](https://user-images.githubusercontent.com/32534197/34530518-b3a9ae92-f0af-11e7-94cf-2b646c16f32a.png)

result:
![image](https://user-images.githubusercontent.com/32534197/34530494-9fcecace-f0af-11e7-9d8a-af3e443cd341.png)

any idea how to treat this best?

regards Michael

**Comment by plumdog** [comment]
I'd suggest that you do this by subclassing `Col` and returning a rendered template.

For example:

```python
from flask_table import Table, Col
from flask import Flask, render_template_string

app = Flask(__name__)

HTML_STRING = '''
<html>
  <body>
    {{ table }}
  </body>
</html>
'''

SELECT_TEMPLATE_STRING = '''
<select>
{% for value, display in options %}
    <option value="{{ value }}">{{ display }}</option>
{% endfor %}
</select>
'''

class SelectCol(Col):

    def __init__(self, *args, **kwargs):
        self.options = kwargs.pop('options')
        super(SelectCol, self).__init__(*args, **kwargs)

    def td_contents(self, item, attr_list):
        return render_template_string(
            SELECT_TEMPLATE_STRING,
            options=self.options)


SELECT_OPTIONS = [
    ('a', 'AAA'),
    ('b', 'BBB'),
]


class MyTable(Table):
    name = Col('Name')
    select = SelectCol('Select', options=SELECT_OPTIONS)


@app.route('/')
def index():
    items = [
        dict(name='name1'),
        dict(name='name2'),
    ]
    table = MyTable(items)
    return render_template_string(HTML_STRING, table=table)


if __name__ == '__main__':
    app.run(debug=True)
```

I'm using `render_template_string` rather than separate template files, just because it makes for a simpler example.

Hopefully that helps you get a `<select>` into a `<td>`. If there's more to what you're trying to achieve, perhaps you could copy+paste a self-contained example, if possible.

**Comment by elgaucho79** [comment]
Thanks Andrew,

works well so far. I may come back with other things soon. :-)

regards
Michael

**Comment by elgaucho79** [comment]
Hi Andrew,

in order to work with the selected options in the subclass, I need unique identifiers/name for the html select element for each row in flask_table. Such as 

`<select id=01, name=whatever>...`

So, I wonder if there is a way to define unique **'id'** and **'name'** for each table row I create.

Thanks
Michael

**Comment by lormayna** [comment]
Ok, your solution seems working fine.
Thank you for help :)

**Comment by elgaucho79** [comment]
Thanks. All 3 working fine.  I also prefer solution 3. will take some to implement it in the way I need. Thank you very much.
