### ISSUE TITLE
ButtonCol - anchor_attr and Column naming

### ISSUE THREAD

**Issue by elgaucho79** [plumdog/flask_table#96]
Hi Andrew,

I have 2 topics in regards to ButtonCol functionalities:

1.
I am trying to use the anchor_attr to specify a bootstrap Class for the button but it seems he is ignoring it:

coding:
![image](https://user-images.githubusercontent.com/32534197/34532709-664855f6-f0b7-11e7-9474-fa2739c37775.png)

result:
![image](https://user-images.githubusercontent.com/32534197/34532730-7308e5da-f0b7-11e7-8427-7f5c85014614.png)

html:
![image](https://user-images.githubusercontent.com/32534197/34532782-b3415542-f0b7-11e7-9381-29d839c6d6bb.png)

2.
further I am trying to give the column header a different name, but he is using the '+' for both, column-header and the button itself. 
Would like to name the column-header 'Action' and the buttons with a '+'.

Thanks for the support
Michael

**Comment by plumdog** [comment]
1. For `ButtonCol`, use `button_attrs` instead. (If you were using `LinkCol`, you'd want `anchor_attrs`).

2. The heading is always taken from the first argument to the column. Then for `LinkCol` and `ButtonCol` they default to using the same for each link/button, but if you use the `text_fallback` kwarg, you can override this.

Example to show both 1 and 2:

```python
from flask_table import Table, ButtonCol, Col
from flask import Flask, request

app = Flask(__name__)

@app.route('/')
def index():
    items = [
        dict(id=1),
        dict(id=2),
    ]
    return MyTable(items).__html__()

@app.route('/item/', methods=['POST'])
def button_target():
    return u'Querystring: {args}'.format(args=request.args)

class MyTable(Table):
    id = Col('ID')
    button = ButtonCol(
        'Heading +',
        'button_target',
        url_kwargs=dict(id='id'),
        text_fallback='Button +',
        button_attrs={'class': 'btn'})

app.run(debug=True)
```

Which creates a table that looks like:
```html
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Heading +</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>
        <form action="/item/?id=1" method="post">
          <button class="btn" type="submit">Button +</button>
        </form>
      </td>
    </tr>
    <tr>
      <td>2</td>
      <td>
        <form action="/item/?id=2" method="post">
          <button class="btn" type="submit">Button +</button>
        </form>
      </td>
    </tr>
  </tbody>
</table>
```

**Comment by elgaucho79** [comment]
Hi Andrew,
1. is working fine. :-)
2. I got an error using text_fallback. May be in relation to my dyntable:

Code:
![image](https://user-images.githubusercontent.com/32534197/34536798-a00678b8-f0c6-11e7-8643-b67d9d0fff8e.png)

error when starting the page:
TypeError: __init__() got an unexpected keyword argument 'text_fallback'

**Comment by plumdog** [comment]
I suspect that means you have an older version of flask table. The `text_fallback` option only arrived in [0.5.0](https://github.com/plumdog/flask_table/blob/master/CHANGELOG.md#050).

**Comment by elgaucho79** [comment]
Yepp. Works now.
